FROM python:3.9-slim

WORKDIR /app

COPY . /app

# Instalamos las dependencias del sistema necesarias para psycopg2 y compilación
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Instalamos las dependencias Python
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 3201

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "3201", "--reload"]
